### ISSUE TITLE
[ROADMAP] Path to v2 and official release

### ISSUE THREAD

**Issue by omariosouto** [skynexui/components#51]
## Why
- MVP for allow me to release a small app with it

## How
- [ ] Style: `overflow scroll` with list view under the hood;
- [ ] Style: `borderRadius Left|Right|Top|Bottom` supporting string to enable fine tuning in future;
- [ ] Style: `boxShadow` supporting string to enable fine tuning in future;
- [ ] Component: `Image`
- [ ] Component: `TextField`
- [ ] Component: `Button`
- [ ] Component: `Icon`

## Definition of Done
- To have all **How** topics implemented
